name: Review Doc
run-name: ${{ github.actor }} is syncing doc and code
on: [pull_request]
jobs:
  Print-On-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 1 #0 - for blocker, 1 for non-blocker
