name: Review Doc on PR
run-name: ${{ github.actor }} is syncing doc and code
on: [pull_request, issue_comment]
jobs:
  pr_doc_sync:
    name: pr doc sync
    if: |
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        startsWith(github.event.comment.body, 'document updated')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git --no-pager log -n 10
          git status
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 0 #0 - for blocker, 1 for non-blocker
  pr_commented_doc_update_nr:
    name: pr comment doc update not required
    if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, 'document update not required')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.comment.body }}
          # run code to pass check
