name: Review Doc on PR
run-name: ${{ github.run_id }} is syncing doc and code
on: [pull_request]
jobs:
  pr_doc_sync:
    name: pr doc sync
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 0 #0 - for blocker, 1 for non-blocker
