name: Review Doc on Comment
run-name: ${{ github.actor }} is syncing doc and code
on: 
  issue_comment:
    types: [created]
jobs:
   pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }} && contains("Sync Again", ${{ github.event.comment.body }})
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.comment.body }}
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 0 #0 - for blocker, 1 for non-blocker
    
          
      
