name: Review Doc on Comment
run-name: ${{ github.actor }} is syncing doc and code
on: 
  issue_comment:
    types: [created]
jobs:
   pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
      - run: |
          echo ${{ github.event.comment.body }}
        env:
          NUMBER: ${{ github.event.issue.number }}  
          
      
