name: Review Doc on PR
run-name: ${{ github.actor }} is syncing doc and code
on: [pull_request, issue_comment]
jobs:
  pr_doc_sync:
    name: pr doc sync
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 0 #0 - for blocker, 1 for non-blocker
  pr_comment_sync:
    name: pr comment doc sync
    if: github.event_name == 'issue_comment' && contains(${{ github.event.comment.body }} == 'Doc Updated. Sync Again')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.comment.body }}
          echo ${{ github.event_name }}
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync Docs
        uses: knowl-doc/sync-docs@master
        with:
          knowl_api_key: ${{secrets.KNOWL_API_KEY}}  
          action_type: 0 #0 - for blocker, 1 for non-blocker
  pr_commented_doc_update_nr:
    name: pr comment doc update not required
    if: github.event_name == 'issue_comment' && contains(${{ github.event.comment.body }} == 'Doc Update Not Required')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.comment.body }}
          echo ${{ github.event_name }}
          # run code to pass check
